---
title: "Case Study: BellaBeat"
author: "Kahlyll Wilson"
date: "`r format(Sys.time(), '%B %d , %Y')`"
output: pdf_document
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### NOTE: code and files can be found in [Github Repository](https://github.com/Kwilso3412/Case_Study_BellaBeat)
## Overview

The following case study was completed apart of the Google Data Analytics Professionals course. It is based on the fictional Company BellaBeat a high-tech manufacturer of health-focused products for women. 

In this scenario I was tasked with helping Bellabeat become a potential big player in the global smart device market. The Cofounder and Chief Creatitve Officer,Urška Sršen, believes that analyzing smart device fitness data could help unlock new growth opportunites for the company. Along with Sršen another key stake holder is Sando Mur a mathmetichian and Bellabeats cofounder. 

The company offers a variety of products such as:

* Bellabeat App
* Leaf: a classic wellness tracker
* Time: a wellness watch combines timeless look of a classic timepiece with smart technology
to track user activity
* Spring: This is a water bottle that tracks daily water intake using smart technology
* Bellabeat membership: a subscription-based membership program for users.

## Buisness Task

In this scenario I have been tasked with completing the following requirements for the key stakeholders:

1. Analyze smart device usage data in order to gain insight into how consumers use non-Bellabeat smart devices.
2. select one Bellabeat product to apply these insights to in your presentation

Through completing the tasks this report will explain to key stakeholders:

1. What are some trends in smart device usuage?
2. How could the trends apply to the bellabeat customer?
3. How can both my team members and stakeholders use these insishts to make data driven decisoins


## Analysis

### Data gathering and cleaning phase
The analysis was completed using the [FitBit Fitness Tracker Data (FFTD)](https://www.kaggle.com/datasets/arashnic/fitbit). The FFTD dataset is open to the public and can be found on the [Kaggle website](https://www.kaggle.com/#). 

For the analysis I first cleaned and organized the data using excel when I pulled the raw data file from FFTD I noticed that there were multiple spread sheets that had overlapping data. To make sure I was not looking at repeated data I combined all of them into one file using the XLOOKUP function. Using this feature I was able to bring in the data from [the four spread sheets and compile it into one data set](https://github.com/Kwilso3412/Case_Study_BellaBeat/tree/main/FitBit%20Tracker%20data) that I could analyze. 

During this stage I noticed something interesting from the data. When it came to overall logging the active distance with the fitness tracker it was very rare or noe at all. There were also inconsistent metrics being recorded when users are either Very active or Moderately active. However, when it it came to light active distance tracking, the results were overwhelmingly positive. With showing results that at least everyday each user was engagin in light activity. 


### Analysis phase

### How anlaysis was conducted

For the analysis portion of this case study it was completed using [SQL and BigQuery database](https://github.com/Kwilso3412/Case_Study_BellaBeat/tree/main/SQL%20Query%20Code). 

I broke the large data down to answer the query's below 
  * What was the Average activity per day?
  * What was each users Average Activity?
  * What was the Average of all the users?
  
Once I had my results I took them out of the data base and stored them in a [seperate folder](https://github.com/Kwilso3412/Case_Study_BellaBeat/tree/main/SQL%20Query%20Code/Results). Then Used a combination of R and Tableu to visualize the results. 

### Results 




## Conclusions
